# Generated by Django 4.2 on 2026-04-16 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_slidecontent_source_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='slidecontent',
            name='processed_image_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
