# Generated by Django 4.2 on 2026-04-18 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0004_slidecontent_processed_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="slidecontent",
            name="translated_notes",
            field=models.TextField(blank=True, default=""),
        ),
    ]
