# Generated by Django 4.2 on 2026-04-18 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0005_slidecontent_translated_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="summaryrecord",
            name="mind_map",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
